#!/usr/bin/env bash

USAGE="Usage: generate_credentials -l <user list> [-o <outdir>] \n
\n
This command generates credentials for users\n
\n
-l  tab-delimited list of users, with 2 columns: first name and last name. Required. \n
-o  output directory. Default: ./credentials \n
-p  port start. Generates ports and starts counting from this port. E.g. for Rstudio server count from 9001. Default: 10001\n
-a  address to use in the link (usually IP address). Required."

while getopts ":l:o:p:a:" opt
do
  case $opt in
    l)
      LIST=$OPTARG
      ;;
    o)
      OUTDIR=$OPTARG
      ;;
    p)
      PORTSTART=$OPTARG
      ;;
    a)
      IP=$OPTARG
      ;;
    \?)
      echo -e "Invalid option: -$OPTARG \n" >&2
      echo -e $USAGE >&2
      exit 1
      ;;
    :)
      echo -e "Option -$OPTARG requires an argument. \n"
      echo -e $USAGE >&2
      exit 1
      ;;
  esac
done

# return usage if no options are passed
if [ $OPTIND -eq 1 ]
then
  echo -e "No options were passed. \n" >&2
  echo -e $USAGE >&2
  exit 1
fi

# required options
if [ "$LIST" == "" ]; then echo "option -l is missing, but required">&2 && exit 1; fi
if [ "$IP" == "" ]; then echo "option -a is missing, but required">&2 && exit 1; fi

# default values
if [ "$OUTDIR" == "" ]; then OUTDIR=./credentials; fi
if [ "$PORTSTART" == "" ]; then PORTSTART=10001; fi

# get script source directory to not break secondary script dependencies
SOURCEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

TMPULIST=`mktemp`
TMPTNAMES=`mktemp`
TMPUNAMES=`mktemp`
TMPPASSWD=`mktemp`
TMPCOMB=`mktemp`
TMPPORT=`mktemp`

mkdir -p $OUTDIR


# check if end of file new line exists
# and add it if not
cat $LIST | tail -c1 | read -r _ || echo >> $LIST

# removing carriage returns and spaces
cat $LIST | tr -d '\015\040' > $TMPULIST

LIST=$TMPULIST

FIRSTL=`cat "$LIST" | cut -f 1 | tr -cd '\11\12\15\40-\176' | tr [:upper:] [:lower:] | cut -c-1`
LASTN=`cat "$LIST" | cut -f 2 | tr -cd '\11\12\15\40-\176' | tr [:upper:] [:lower:]`

USERNAMES=$(paste -d '-' <(echo "$FIRSTL") <(echo "$LASTN") | tr -d '-')

cat "$LIST" > $TMPTNAMES

paste $TMPTNAMES <(echo $USERNAMES | tr ' ' '\n') >> $TMPUNAMES

rm $TMPTNAMES

# generate empty password file
if [ -f $TMPPASSWD ]
then
  rm $TMPPASSWD
  touch $TMPPASSWD
fi

for user in $USERNAMES
do
    openssl rand -base64 14 >> $TMPPASSWD
done

paste $TMPUNAMES $TMPPASSWD > $TMPCOMB

cat $TMPCOMB \
| awk -v portstart=$PORTSTART -v address=$IP -v OFS='\t' \
'{print NR+portstart-1, "http://"address":"NR+portstart-1, $0}' \
> $TMPPORT

cat $TMPPORT | cut -f 1,5,6 > $OUTDIR/input_docker_start.txt

cat $TMPPORT | awk -v OFS='\t' 'BEGIN {print "first", "last", "password", "link"}{print $3, $4, $6 ,$2}' > $OUTDIR/user_info.txt

rm $TMPULIST $TMPPASSWD
